### ISSUE TITLE
App doesn't compile with xcode 6.4

### ISSUE THREAD

**Issue by btelintelo** [Sitecore/sitecore-ios-sdk-sample#4]
Fails in the prefix header on     #import SitecoreMobileSDK/SitecoreMobileSDK.h

**Comment by Igor-Khomich** [comment]
I have checked it with Xcode Version 6.4 (6E35b)
Application was build successfully. 
Please clean up your DerivedData folder and try again. Thanks.

**Comment by Igor-Khomich** [comment]
Xcode 6 compatibility was fixed
